name: Jest coverage
description: Report

inputs:
  skip_on:
    description: The label used for skipping verification
    required: false
  jest:
    description: The jest command to run
    required: false
    default: jest
  scope:
    description: An extra name to add in the comment header
    required: false

runs:
  using: node12
  main: dist/index.js

branding:
  icon: git-branch
  color: gray-dark
